/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TWITTERBOTADAPTOR_H
#define TWITTERBOTADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.TwitterBot
 */
class TwitterBotAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.TwitterBot")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.TwitterBot\">\n"
"    <method name=\"quit\"/>\n"
"  </interface>\n"
        "")
public:
    TwitterBotAdaptor(QObject *parent);
    virtual ~TwitterBotAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void quit();
Q_SIGNALS: // SIGNALS
};

#endif
